version: '3.3'
services:
  app:
    container_name: concordia
    restart: on-failure
    build: .
    ports:
    - '3000:3000'
    env_file:
    - .env
    links:
    - database
    command: ['npm', 'start']
  database:
    image: postgres:10
    ports:
    - '11543:5432'
    volumes:
    - ./scripts:/docker-entrypoint-initdb.d
    - database-data:/var/lib/postgresql/data
  nginx:
    build: nginx
    ports:
      - "80:80"
    links:
      - app
volumes:
  database-data: {}
